controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/login
    methods: ['POST']    
    defaults:
        _format: json 